Repository falansari/car_reservation_system_web, pull requests merged in 2018-06, with the labels that each got.

#44 Issue7 Homepage closes #7
  Database.php
  db/proc_available_car_categories_list.sql
  db/proc_cars_list_search.sql
  db/proc_manufacturers_list_with_available_cars.sql
  index.php
  models/Cars.php
  models/Categories.php
  models/Manufacturers.php
  models/Models.php
  models/Years.php
  search.php
Labels: enhancement

#50 [hotfix] updated login #47
  Header.php
  Login.php
  LoginPage.php
  Register.php
  css/cars.css
Labels: hotfix

#49 full admin board #48
  AddAccessory.php
  AddCar.php
  AddCategory.php
  AddManufacture.php
  AddModel.php
  AdminAlter.php
  AdminCars.php
  AdminHeader.php
  AdminHome.php
  CarCategories.php
  CarManufacture.php
  DeleteAccessory.php
  DeleteCategory.php
  DeleteModel.php
  Deletemanufacturer.php
  Dropdownfunctions.php
  EditAccessory.php
  EditCars.php
  EditCategory.php
  EditModel.php
  Editmanufacturer.php
  MonthlyRevenue.php
  MostPopular.php
  carAccessories.php
  carModel.php
  css/cars.css
  deleteCar.php
  images/edit.png
Labels: enhancement

#54 Issue43 Search results page
  css/pagination.css
  css/table.css
  db/select_car_search_query.sql
  models/Cars.php
  search.php
Labels: enhancement

#56 Issue8 Create Reservation Page
  AdminHeader.php
  Header.php
  css/table.css
  db/car_reservation_system.sql
  db/select_car_search_query.sql
  db/trig_add_new_sale.sql
  db/trig_delete_cancelled_sale.sql
  models/Cars.php
  models/Categories.php
  reserve.php
  search.php
Labels: enhancement

#57 Issue19 Car Accessories Page
  accessories.php
  db/car_reservation_system.sql
  models/Accessories.php
Labels: enhancement

#59 Issue19 Car Accessories Page fixed
  accessories.php
  db/car_reservation_system.sql
  models/Accessories.php
Labels: enhancement

#62 moved OR statements to bottom of select query fixes #61
  models/Cars.php
Labels: hotfix

#63 Issue9 Checkout Page
  checkout.php
  customerinfo.php
  models/Accessories.php
  models/Cars.php
  models/Countries.php
Labels: enhancement

#64 Issue10 Payment Page
  db/car_reservation_system.sql
  models/Accessories.php
  models/CardProviders.php
  models/Countries.php
  models/PaymentTypes.php
  payment.php
  summary.php
Labels: enhancement

#65 Issue20 Booking Summary Page
  customerinfo.php
  models/Reservations.php
  payment.php
  summary.php
Labels: enhancement

#73 Issue28 README.md
  README.md
Labels: docs
