Repository falansari/car_reservation_system_web, pull requests merged in 2018-05, with the labels that each got.

#23 db schema design complete closes #4
  docs/Online Car Reservation System Schema.erdplus
  docs/erdplus-diagram.png
Labels: docs

#24 added image field to cars #4
  docs/Online Car Reservation System Schema.erdplus
  docs/erdplus-diagram.png
Labels: docs

#26 navigation bar complete #1
  public_html/Header.php
  public_html/css/cars.css
  public_html/images/back.jpg
  public_html/index.php
Labels: CSS, HTML, PHP, enhancement

#27 site design complete closes #2
  public_html/About.php
  public_html/LoginFunctions.php
  public_html/LoginPage.php
  public_html/Register.php
Labels: enhancement

#31 Issue5
  db/car_reservation_system.sql
  db/create_db_tables_script.sql
  db/insert_db_default_data_script.sql
  db/trig_add_default_user_role.sql
  db/trig_add_new_car_total_reservations_count.sql
  db/trig_add_new_sale.sql
  db/trig_delete_cancelled_sale.sql
  db/trig_delete_existing_car_total_reservations_count.sql
  db/trig_delete_user_role.sql
  db/trig_reduce_existing_car_total_reservations_count.sql
  db/trig_update_existing_car_total_reservations_count.sql
Labels: MySQL, enhancement

#33 site design updated closes #2
  css/cars.css
  images/car-rental-5-cars.png
Labels: CSS

#36 Issue13 Registration Page
  Register.php
  Users.php
Labels: enhancement

#38 Issue37 Database Class
  Database.php
  db/proc_cars_list_search.sql
  db/select_car_search_query.sql
  index.php
  models/Cars.php
Labels: enhancement

#40 Issue39 [bug] Wrong data entry, Typos & other issues in Registration Function
  Register.php
  Users.php
Labels: hotfix
